# Generated by Django 3.0.7 on 2020-08-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200816_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=70)),
                ('address2', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('totalprice', models.FloatField(default=0)),
                ('phone', models.PositiveIntegerField()),
                ('order_date', models.DateField()),
            ],
        ),
    ]
