# Generated by Django 3.0.7 on 2020-08-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customer_email',
        ),
    ]
