# Generated by Django 3.0.7 on 2020-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200817_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='totalprice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
