# Generated by Django 3.0.7 on 2020-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=70)),
                ('message', models.CharField(max_length=300)),
                ('phone', models.PositiveIntegerField()),
                ('contact_date', models.DateField()),
            ],
        ),
    ]
