# Generated by Django 3.0.7 on 2020-08-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
    ]
